MoviesBundle\Entity\Movie:
    type: entity
    table: movie
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            lenght: 45
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        releaseDate:
            type: datetime
            nullable: true
        genre:
            type: string
            lenght: 255
        synopsis:
            type: string
            lenght: 255
            nullable: true
        promotionalArt:
            type: string
            lenght: 255
            nullable: true
        rating:
            type: float
            nullable: true
        trailer:
            type: string
            nullable: true
    manyToOne:
        producer:
            targetEntity: Producer
            inversedBy: movies
            joinColumn:
                name: producer_id
                referencedColumnName: id
    oneToOne:
        director:
              targetEntity: Person
              joinColumn:
                  name: director_id
                  referencedColumnName: id
    manyToMany:
        actors:
              targetEntity: Person
              joinTable:
                  name: movies_actors
                  joinColumns:
                      movie_id:
                          referencedColumnName: id
                  inverseJoinColumns:
                      actor_id:
                          referencedColumnName: id
                          unique: true

