MoviesBundle\Entity\Producer:
    type: entity
    table: producer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
        fields:
            name:
                type: string
                lenght: 45
            createdAt:
                type: date
            updatedAt:
                type: date
        manyToOne:
                movie:
                  targetEntity: Movie